### ISSUE TITLE
基于windows gdi+的常用自绘控件

### ISSUE THREAD

**Issue by Humorly** [Humorly/windows-ui#1]
1：通过对UI（CDialog(CWnd) -> CButton(CImageButton) -> CRaidoButton -> CCheckButton -> CSpinButton -> CComboBox -> CStatic）等的重绘，实现MFC常用控件的自定义。

**Comment by Humorly** [comment]
![psb](https://user-images.githubusercontent.com/12562039/53156598-b36ef400-35fa-11e9-99fa-918ede0b75e4.png)

**Comment by Humorly** [comment]
![123 2](https://user-images.githubusercontent.com/12562039/53156709-efa25480-35fa-11e9-9af7-4ccf42f4d5be.jpg)

**Comment by Qianzujin** [comment]
跑不动呀，大佬 救救我吧  我继承了一个你自绘的button类 然后再precreate那里调用了你写的set图片的路径方法，但是还是运行不了呀
![image](https://user-images.githubusercontent.com/49854479/59238623-5e023580-8c31-11e9-9a4d-0d6e5e8be633.png)到这里就卡住了

**Comment by Qianzujin** [comment]
我是个菜鸡  救救我吧

**Comment by Humorly** [comment]
> 我是个菜鸡 救救我吧

继承自 ImageButton?可否贴出precreate里set的调用代码？

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/59241010-8c374380-8c38-11e9-935e-ff1bbe753677.png)

**Comment by Humorly** [comment]
@Qianzujin SetButtonImage有没有触发断言？

**Comment by Humorly** [comment]
@Qianzujin 使用gdi+库需要注意先初始化gdi+对象
1.包含GdiPlusMakeUi.h -> #include "GdiPlusMakeUi.h"
![image](https://user-images.githubusercontent.com/12562039/59242258-78daa700-8c3d-11e9-81e1-5ffe255ad6c4.png)
我这里在测试窗体中包含此gdi头文件；

2.在合适的位置初始化gdi+ -> CGdiPlusMakeUi::CGdiPlusMakeUiInit();
![image](https://user-images.githubusercontent.com/12562039/59242294-8c860d80-8c3d-11e9-8cd7-c7d040e61f6c.png)
在窗体的初始化中调用该初始过程；

**Comment by Humorly** [comment]
@Qianzujin 之后方可使用对应的自绘控件，另外button需要被自绘制的话，要设置button本身的属性为Owner Draw为true，
![image](https://user-images.githubusercontent.com/12562039/59242372-da027a80-8c3d-11e9-855b-ba9907821354.png)

**Comment by Humorly** [comment]
@Qianzujin 本UI库中的所有自绘控件绘制方式，均使用Windows中的gdi+库自带的相关对象，例如gdi::image，可以看看gdi+对应的使用方式。

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/59243209-534f9c80-8c41-11e9-9033-9f9a3f7fe054.png)
搞腚了  谢谢大佬

**Comment by Qianzujin** [comment]
就是oninit哪里没有写

**Comment by Humorly** [comment]
> ![image](https://user-images.githubusercontent.com/49854479/59243209-534f9c80-8c41-11e9-9033-9f9a3f7fe054.png)
> 搞腚了 谢谢大佬



> ![image](https://user-images.githubusercontent.com/49854479/59243209-534f9c80-8c41-11e9-9033-9f9a3f7fe054.png)
> 搞腚了 谢谢大佬

\(^o^)/~

**Comment by Qianzujin** [comment]
请问大佬还有没有别的自绘控件呀。。。。  你的控件我都用上了  都挺好用

**Comment by Humorly** [comment]
> 请问大佬还有没有别的自绘控件呀。。。。 你的控件我都用上了 都挺好用

木有了
