### ISSUE TITLE
关于开源协议

### ISSUE THREAD

**Issue by skyZhiHe** [Humorly/windows-ui#4]
因为想用来美化一下公司MFC软件，所以问一下开源协议。是属于作者免责，使用随意？

**Comment by Humorly** [comment]
> 因为想用作美化一下公司MFC软件，所以问一下开源协议。是属于作者免责，使用随意？

值得指出的是，本开源中唯一一个第三方控件是CButtonST，此库作者声明：

----------------------------------------------------
此软件对于个人使用或免费应用程序是免费的。
如果您在商业或共享应用程序中使用此软件，
恳请向作者捐款5美元（5美元）。
----------------------------------------------------

在商用软件中稳妥起见可以移除该控件，或参考其源码更改。
除此之外其他控件为本人原创，可以随意使用，没有任何授权限制。

**Comment by skyZhiHe** [comment]
那个主菜单怎样绘制在下方的，和最小化按钮一行。想美化一个具有最大化，滚动条，可拉伸，有主菜单的mfc程序，感觉挺麻烦的，大佬有类似的程序框架吗

**Comment by Humorly** [comment]
> 那个主菜单怎样绘制在下方的，和最小化按钮一行。想美化一个具有最大化，滚动条，可拉伸，有主菜单的mfc程序，感觉挺麻烦的，大佬有类似的程序框架吗

菜单位置无法调整，想实现所说的必须自定义一块区域来绘制自定义菜单并维护对应位置点击事件，这个比较麻烦。

实现最大化可拉伸解开注释
// 区域设定
LRESULT COwnerDrawWindowDlg::OnNcHitTest(CPoint point)
{
	// 获取结果
	LRESULT lResult = CalcWindowHitWhere();
	// 重新计算位置
	if (HTCAPTION == lResult || HTTOPLEFT == lResult || HTLEFT == lResult || HTBOTTOMLEFT == lResult || HTBOTTOM
		||
		HTBOTTOMRIGHT == lResult || HTRIGHT == lResult || HTTOPRIGHT || HTTOP == lResult
		)
	{
		return lResult;
	}
	return CDialogEx::OnNcHitTest(point);
}
窗口即可拉伸。

调整接口
void COwnerDrawWindowDlg::OnBnClickedMax()
{
	ShowWindow(SW_SHOWMAXIMIZED);
	m_pWidgitBtn[1]->ShowWindow(false);
	m_pWidgitBtn[2]->ShowWindow(true);
}

void COwnerDrawWindowDlg::OnBnClickedRestore()
{
	ShowWindow(SW_RESTORE);
	m_pWidgitBtn[1]->ShowWindow(true);
	m_pWidgitBtn[2]->ShowWindow(false);
}
窗口可以最大化/还原。

由于没有做窗体size变更的捕获，所以导致窗口最大化/拉伸时界面控件不会主动跟随，如果要实现这些功能，必须重载窗体OnSize方法让窗体上子控件位置跟随主窗体动态变更，这里没有予以实现。

需要做高度自定义的mfc界面 可以使用duilib。
